export const technicalSkills = [
  "JavaScript",
  "Java",
  "ReactJs",
  "Typescript",
  "HTML",
  "CSS",
  "ES6",
  "Sass",
  "Jest",
  "React testing library",
  "React-Redux",
  "Axios",
  "NPM ",
  "Bootstrap",
  "i18Next",
  "Git",
  "Sonar",
  "Android App Development",
  "Design Patterns & Principles",
  "Data Structures & Algorithms",
];

export const toolsNTechnology = [
  "Docker",
  "CI/CD",
  "GitHub",
  "Splunk",
  "VS Code",
  "IntelliJ Idea",
  "NetBeans",
  "Unleash",
  "Zeplin",
  "Android Studio",
];
